apiVersion: apps/v1
kind: Deployment
metadata:
  name: notjira-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notjira-gateway
  template:
    metadata:
      labels:
        app: notjira-gateway
    spec:
      containers:
      - name: notjira-gateway
        image: milosky/notjira-gateway:latest
        ports:
        - containerPort: 8000
        env:
        - name: AMQP_URL
          value: "amqp://localhost:5672"
        - name: JWT_SECRET
          value: "123456"
---
apiVersion: v1
kind: Service
metadata:
  name: notjira-gateway
spec:
  type: NodePort
  externalIPs:
    - 192.168.1.100
  selector:
    app: notjira-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30001 # Puedes elegir un puerto en el rango 30000-32767
